config/routes.rb
Rails.application.routes.draw do

  get 'places/index'

  get 'places/show'

  get 'places/new'

  get 'places/create'

  get 'places/edit'

  get 'places/update'

  get 'places/destroy'

  get 'placescategories/index'

  get 'placescategories/show'

  get 'placescategories/new'

  get 'placescategories/create'

  get 'placescategories/edit'

  get 'placescategories/update'

  get 'placescategories/destroy'

  get 'restaurantopeninghours/index'

  get 'restaurantopeninghours/show'

  get 'restaurantopeninghours/new'

  get 'restaurantopeninghours/create'

  get 'restaurantopeninghours/edit'

  get 'restaurantopeninghours/update'

  get 'restaurantopeninghours/destroy'

  get 'menuscomments/index'

  get 'menuscomments/show'

  get 'menuscomments/new'

  get 'menuscomments/create'

  get 'menuscomments/edit'

  get 'menuscomments/update'

  get 'menuscomments/destroy'

  get 'menus/index'

  get 'menus/show'

  get 'menus/new'

  get 'menus/create'

  get 'menus/edit'

  get 'menus/update'

  get 'menus/destroy'

  get 'meals/index'

  get 'meals/show'

  get 'meals/new'

  get 'meals/create'

  get 'meals/edit'

  get 'meals/update'

  get 'meals/destroy'

  get 'restaurants/index'

  get 'restaurants/show'

  get 'restaurants/new'

  get 'restaurants/create'

  get 'restaurants/edit'

  get 'restaurants/update'

  get 'restaurants/destroy'

  get 'campusunits/index'

  get 'campusunits/show'

  get 'campusunits/new'

  get 'campusunits/create'

  get 'campusunits/edit'

  get 'campusunits/update'

  get 'campusunits/destroy'

  get 'wellcome/index'

  root 'welcome#index'

  resources :campusunits, :path => "campus"
  resources :restaurants, :path => "restaurante"
  resources :restaurantopeninghours, :path => "horariosrestaurante"
  resources :meals, :path => "refeicao"
  resources :menus, :path => "cardapio"
  resources :menuscomments, :path => "comentariosrefeicao"
  resources :placescategories, :path => "categoriaslocal"
  resources :places, :path => "local"

  namespace :api, defaults: {format: 'json'}  do
      resources :campusunits, :path => "campus"
      resources :meals, :path => "refeicao"
  end

end

app/models/meal.rb
# -*- encoding : utf-8 -*-
class Meal < ActiveRecord::Base

  validates_presence_of :name

  has_many :menus
  has_many :openinghours
end

app/controllers/api/meals_controller.rb
# -*- encoding : utf-8 -*-
module Api
  class MealsController < ApplicationController

    respond_to :json
    def index
      respond_with Meal.all
  end

  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @meal }
      format.json { render :json => @meal.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} }
    end
  end

  def new
    @meal = Meal.new

    respond_to do |format|
      format.html #new.html.erb
      format.json { render :json => @meal.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} }
    end
  end

  def create
    @meal = Meal.new(params[:meal])

    respond_to do |format|
      if @meal.save
        format.html { redirect_to(@meal,
          :notice => 'Refeição adicionada com sucesso.') }
        format.json { render :json => @meal.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")},
        :status => :created, :location => @meal }
      else
        format.html { render :action => "new" }
        format.json { render :json => @meal.errors,
          :status => :unprocessable_entity }
        end
      end
    end

    def edit
      @meal = Meal.find(params[:id])
    end

    def update
      @meal = Meal.find(params[:id])

      respond_to do |format|
        if @meal.update_attributes(params[:meal])
          format.html { redirect_to(@meal,
            :notice => 'A refeição foi atualizada com sucesso.')}
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @meal.errors.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")},
          :status => :unprocessable_entity }
        end
      end
    end

    def destroy
      @meal = Meal.find(params[:id])
      @meal.destroy

      respond_to do |format|
        format.html { redirect_to meals_url }
        format.json { head :no_content }
      end
    end

  end
end

app/controllers/meals_controller.rb
# -*- encoding : utf-8 -*-
class MealsController < ApplicationController

  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  def index
    @meals = Meal.all
  end

  def show
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to(@meal, :notice => 'Refeição adicionada com sucesso.')
    else
      render :action => "new"

    end
  end

  def edit
  end

  def update
    if @meal.update(meal_params)
      redirect_to(@meal, :notice => 'A refeição foi atualizada com sucesso.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @meal.destroy
    redirect_to meals_url
  end

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:name, :cost)
  end

end

app/helpers/meals_helper.rb
# -*- encoding : utf-8 -*-
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
<% if @meal.errors.any? %>
<div id="explicacao_erro">
	<h2>Devido a estes <%= pluralize(@meal.errors.count, "error") %>
		esta nova refeição não pode ser salva:</h2>

		<ul>
			<% @meal.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class='row' >
		<div class='col-sm-6' >
			<div class='form-group'>
				<%= f.label :name %><br />
				<%= f.text_field :name ,:class => "form-control" %>
			</div>
		</div>
	</div>
	<div class='row' >
		<div class='col-sm-6' >
			<div class='form-group'>
				<%= f.label :cost %><br />
				<%= f.text_field :cost ,:class => "form-control"  %>
			</div>
		</div>
	</div>
	<div class='row' >
		<div class='col-sm-6' >
			<div class='form-group'>
				<%= f.submit :class => "btn btn-primary"%>

			<% end %>

app/views/meals/edit.html.erb
<h1>Editando refeições</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @meal, :class => 'btn btn-info' %>
<%= link_to 'Voltar', meals_path, :class => 'btn btn-default' %>

app/views/meals/index.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Refeições</h4></div>

  <table class="table table-striped table-hover" style="width:90%; " align="center" id="tableLevels">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Preço</th>
         <!--<th width="20%"><%#=t '.actions', :default => t("helpers.actions") %></th> -->
      </tr>
    </thead>

    <tbody>
      <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.name %></td>
        <td><%= meal.cost %></td>
        <!-- <td><%#=  link_to 'Edit', edit_level_path(level) , :class => 'btn btn-xs btn-success'  %>
          <%#= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-xs btn-danger' %>
        </td> -->
      </tr>
      <% end %>
    </tbody>
  </table>


<%= link_to 'Nova Refeição', new_meal_path, :class => 'btn btn-xs btn-primary' %>

app/views/meals/new.html.erb
<h1>Nova refeição</h1>

<%= render 'form' %>

<%= link_to 'Voltar', meals_path , :class => 'btn btn-default'%>

</div>
</div>
</div>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Refeição</h1>
<div style="font-size: 18px;">
	<p>
		<b>Nome:</b>
		<%= @meal.name %>
	</p>

	<p>
		<b>Preço:</b>
		<%= @meal.cost %>
	</p>
</div>
<%= link_to 'Editar', edit_meal_path(@meal), :class => "btn btn-primary" %>
<%= link_to 'Remover', @meal, :confirm => 'Tem certeza?', :method => :delete, :class => "btn btn-danger" %>
<%= link_to 'Voltar', meals_path, :class => "btn btn-default" %>