config/routes.rb
Rails.application.routes.draw do

  get 'places/index'

  get 'places/show'

  get 'places/new'

  get 'places/create'

  get 'places/edit'

  get 'places/update'

  get 'places/destroy'

  get 'placescategories/index'

  get 'placescategories/show'

  get 'placescategories/new'

  get 'placescategories/create'

  get 'placescategories/edit'

  get 'placescategories/update'

  get 'placescategories/destroy'

  get 'restaurantopeninghours/index'

  get 'restaurantopeninghours/show'

  get 'restaurantopeninghours/new'

  get 'restaurantopeninghours/create'

  get 'restaurantopeninghours/edit'

  get 'restaurantopeninghours/update'

  get 'restaurantopeninghours/destroy'

  get 'menuscomments/index'

  get 'menuscomments/show'

  get 'menuscomments/new'

  get 'menuscomments/create'

  get 'menuscomments/edit'

  get 'menuscomments/update'

  get 'menuscomments/destroy'

  get 'menus/index'

  get 'menus/show'

  get 'menus/new'

  get 'menus/create'

  get 'menus/edit'

  get 'menus/update'

  get 'menus/destroy'

  get 'meals/index'

  get 'meals/show'

  get 'meals/new'

  get 'meals/create'

  get 'meals/edit'

  get 'meals/update'

  get 'meals/destroy'

  get 'restaurants/index'

  get 'restaurants/show'

  get 'restaurants/new'

  get 'restaurants/create'

  get 'restaurants/edit'

  get 'restaurants/update'

  get 'restaurants/destroy'

  get 'campusunits/index'

  get 'campusunits/show'

  get 'campusunits/new'

  get 'campusunits/create'

  get 'campusunits/edit'

  get 'campusunits/update'

  get 'campusunits/destroy'

  get 'wellcome/index'

  root 'welcome#index'

  resources :campusunits, :path => "campus"
  resources :restaurants, :path => "restaurante"
  resources :restaurantopeninghours, :path => "horariosrestaurante"
  resources :meals, :path => "refeicao"
  resources :menus, :path => "cardapio"
  resources :menuscomments, :path => "comentariosrefeicao"
  resources :placescategories, :path => "categoriaslocal"
  resources :places, :path => "local"

  namespace :api, defaults: {format: 'json'}  do
      resources :campusunits, :path => "campus"
      resources :meals, :path => "refeicao"
  end

end

app/models/restaurant.rb
# -*- encoding : utf-8 -*-
class Restaurant < ActiveRecord::Base

  validates_presence_of :campusunit_id, :name, :address

  belongs_to :campusunit
  has_many :menus
  has_many :openinghours
  has_many :meals
end

app/controllers/api/restaurants_controller.rb
# -*- encoding : utf-8 -*-
module Api
  class RestaurantsController < ApplicationController
    
    before_action :set_restaurant , only: [:show, :edit, :update, :destroy]
    
    class Restaurant < ::Restaurant
      def as_json(options ={})
        super.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")}
      end
    end
    
    respond_to :json
    
    def index
      respond_with Restaurant.all
    end

    def show
      # descobrindo a segunda-feira e o domingo
      @monday = Date.today.beginning_of_week()
      @sunday = @monday + 6
      @menus = Menu.where(:restaurant_id => @restaurant.id).where(:day => (@monday)..(@sunday)).order('meal_id ASC, day ASC')

      @response = {:restaurant => @restaurant, :menus => @menus}

      respond_with @response
    end

    def new
      @restaurant = Restaurant.new
      respond_with @restaurant
    end

    def create
      @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        respond_with @restaurant
      else
        respont_with @restaurant.errors
      end
    end

    def edit
      respont_with @restaurant
    end

    def update

      if @restaurant.update_attributes(restaurant_params)
        respond_with :no_content
      else
        respond_with @restaurant.errors
      end
    end

    def destroy
      @restaurant.destroy
      respond_with :no_content
    end

    private

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
      @campusunit = Campusunit.find(@restaurant.campusunit_id)
      @restaurants = Restaurant.where(:campusunit_id => @campusunit.id)
    end

    def restaurant_params
      params.require(:restaurant).permit(:campusunit_id, :name, :address, :tel)
    end

  end
end

app/controllers/restaurants_controller.rb
 # -*- encoding : utf-8 -*-
class RestaurantsController < ApplicationController
  
  before_action :set_restaurant , only: [:show, :edit, :update, :destroy]
  
  def index
    @restaurants = Restaurant.all
  end

  def show
    # descobrindo a segunda-feira e o domingo
    @monday = Date.today.beginning_of_week()
    @sunday = @monday + 6 
    @menus = Menu.where(:restaurant_id => @restaurant.id).where(:day => (@monday)..(@sunday)).order('meal_id ASC, day ASC')
  end

  def new
    @campusunits = Campusunit.all
    @restaurant = Restaurant.new
  end

  def create
    @campusunits = Campusunit.all
    @restaurant = Restaurant.new(restaurant_params)
    
    if @restaurant.save
      redirect_to(@restaurant, :notice => 'Restaurante adicionado com sucesso.')
    else
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to(@restaurant, :notice => 'O restaurante foi atualizado com sucesso.')   
    else
      render :action => "edit"
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url
  end
  
  private
  
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    @campusunit = Campusunit.find(@restaurant.campusunit_id)
    @restaurants = Restaurant.where(:campusunit_id => @campusunit.id)
  end
  
  def restaurant_params
    params.require(:restaurant).permit(:campusunit_id, :name, :address, :tel)
  end

end

app/helpers/restaurants_helper.rb
# -*- encoding : utf-8 -*-
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
	<% if @restaurant.errors.any? %>
	<div id="explicacao_erro">
		<h2>Devido a estes <%= pluralize(@restaurant.errors.count, "error") %> 
			este novo restaurante não pode ser salvo:</h2>
		
		<ul>
			<% @restaurant.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	
	<div class="campo_form">
		<%= f.label :campusunit %><br />
		<% @campusunits.each_with_index do |r, i| %>
			<%= f.radio_button(:campusunit_id, r.id, :checked => (i == 0 or r.id == @restaurant.campusunit_id)? true:false ) %>
			<%= r.name %><br /> 
		<% end %>
	</div>
	<div class="campo_form">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="campo_form">
		<%= f.label :address %><br />
		<%= f.text_field :address %>
	</div>
	<div class="campo_form">
		<%= f.label :tel %><br />
		<%= f.text_field :tel %>
	</div>
	<div class="botao_enviar">
		<%= f.submit %>
	</div>
<% end %> 

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

Editando restaurante

<%= render 'form' %>

<%= link_to 'Exibir', @restaurant %> |
<%= link_to 'Voltar', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

Novo restaurante

<%= render 'form' %>

<%= link_to 'Voltar', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><center><%= @restaurant.campusunit_id %></center></h1>
<h1><center><%= @restaurant.name %></center></h1>
<h2><center>Endereço: <%= @restaurant.address %></center></h2>
<h2><center>Informações: <%= @restaurant.tel %></center></h2>
<center>
<marquee id="barra_visite_cozinha" scrollamount="4" scrolldelay="45" height="25" width="253" align="center"> VISITE NOSSA COZINHA </marquee>
</center>
<% if @menus.empty? %>

	<h2><center>Não há cardápio para esta semana neste restaurante.</center></h2>

<% else %>

	<p><center>Refeições da semana de <%=@monday.strftime "%d/%m/%Y"%> a <%=@sunday.strftime "%d/%m/%Y"%></center></p> 

	<% cafe_da_manha = @menus.select{ |menu| menu.meal_id.eql? 1 }.length %>
	<% almoco = @menus.select{ |menu| menu.meal_id.eql? 2 }.length %>
	<% jantar = @menus.select{ |menu| menu.meal_id == 3 }.length %>
	
	<div align="center">
	<table border="1">
		<tr>
			<th>Data</th>
			<% if cafe_da_manha > 0 %>	<th>Café da Manhã</th> 	<% end %>
			<% if almoco > 0 %>			<th>Almoço</th> 		<% end %>
			<% if jantar > 0 %>			<th>Jantar</th>			<% end %>
		</tr>
		
		<% (@monday..@sunday).each do |day| %>
		<tr>
			<td width="100px" valign="top">
				<%= "Segunda-Feira" if day.wday == 1	%> 
				<%= "Terça-Feira" 	if day.wday == 2	%>
				<%= "Quarta-Feira" 	if day.wday == 3	%>
				<%= "Quinta-Feira" 	if day.wday == 4 	%>
				<%= "Sexta-Feira" 	if day.wday == 5	%>
				<%= "Sábado" 		if day.wday == 6 	%>
				<%= "Domingo" 		if day.wday == 0	%>
			</td>
			<% (1..3).each do |meal| %>
				<% if (meal == 1 and cafe_da_manha > 0) or 
					  (meal == 2 and almoco > 0) or 
					  (meal == 3 and jantar > 0)   %>
					<td width="300px" height="150px" valign="top">
						<% cardapio = @menus.select{ |menu| menu.day == day and menu.meal_id == meal} %>
						<% if cardapio.length > 0 %>
							<pre class="cardapio_opcoes"><%= cardapio.last.options %></pre>
							<% if cardapio.last.kcal != "" %>
							<p class="cardapio_kcal">Valor calórico de 1 refeição: <%= cardapio.last.kcal %> kcal</p>
							<% end%>
							<%= link_to 'Editar', edit_menu_path(cardapio.last.id) %> 
						<% end %>
					</td>
				<% end %>
			<% end %>
		</tr>
		<% end %>
	
	</table>
	</div>
<% end %>


<center>
	<h3>OBSERVAÇÃO: Cardápio Sujeito a Modificação Sem Prévio Aviso!</h3>
	<br />
	<p>Este cardápio é parte integrante da SAS On-Line!</p>
	<a href="http://www.usp.br/sas" target="_self">www.usp.br/sas</a>
	<p>e será atualizado todas as semanas.</p>
	<br><br>
	<p>Webdesign:</p>
	<a href="mailto:beto@usp.br">Roberto Nunes</a>
</center>

<%= link_to 'Editar', edit_restaurant_path(@restaurant) %> | 
<%= link_to 'Remover', @restaurant, :confirm => 'Tem certeza?', :method => :delete %> | 
<%= link_to 'Voltar', restaurants_path %>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>