config/routes.rb
Rails.application.routes.draw do

  get 'places/index'

  get 'places/show'

  get 'places/new'

  get 'places/create'

  get 'places/edit'

  get 'places/update'

  get 'places/destroy'

  get 'placescategories/index'

  get 'placescategories/show'

  get 'placescategories/new'

  get 'placescategories/create'

  get 'placescategories/edit'

  get 'placescategories/update'

  get 'placescategories/destroy'

  get 'restaurantopeninghours/index'

  get 'restaurantopeninghours/show'

  get 'restaurantopeninghours/new'

  get 'restaurantopeninghours/create'

  get 'restaurantopeninghours/edit'

  get 'restaurantopeninghours/update'

  get 'restaurantopeninghours/destroy'

  get 'menuscomments/index'

  get 'menuscomments/show'

  get 'menuscomments/new'

  get 'menuscomments/create'

  get 'menuscomments/edit'

  get 'menuscomments/update'

  get 'menuscomments/destroy'

  get 'menus/index'

  get 'menus/show'

  get 'menus/new'

  get 'menus/create'

  get 'menus/edit'

  get 'menus/update'

  get 'menus/destroy'

  get 'meals/index'

  get 'meals/show'

  get 'meals/new'

  get 'meals/create'

  get 'meals/edit'

  get 'meals/update'

  get 'meals/destroy'

  get 'restaurants/index'

  get 'restaurants/show'

  get 'restaurants/new'

  get 'restaurants/create'

  get 'restaurants/edit'

  get 'restaurants/update'

  get 'restaurants/destroy'

  get 'campusunits/index'

  get 'campusunits/show'

  get 'campusunits/new'

  get 'campusunits/create'

  get 'campusunits/edit'

  get 'campusunits/update'

  get 'campusunits/destroy'

  get 'wellcome/index'

  root 'welcome#index'

  resources :campusunits, :path => "campus"
  resources :restaurants, :path => "restaurante"
  resources :restaurantopeninghours, :path => "horariosrestaurante"
  resources :meals, :path => "refeicao"
  resources :menus, :path => "cardapio"
  resources :menuscomments, :path => "comentariosrefeicao"
  resources :placescategories, :path => "categoriaslocal"
  resources :places, :path => "local"

  namespace :api, defaults: {format: 'json'}  do
      resources :campusunits, :path => "campus"
      resources :meals, :path => "refeicao"
  end

end

app/models/campusunit.rb
class Campusunit < ActiveRecord::Base

  validates_presence_of :name

  has_many :restaurants
  has_many :places
end

app/controllers/api/campusunits_controller.rb
# -*- encoding : utf-8 -*-
module Api
  class CampusunitsController < ApplicationController
    
    before_action :set_campusunit , only: [:show, :edit, :update, :destroy]
    
    class Campusunit < ::Campusunit
      def as_json(options ={})
        super.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")}
      end
    end

    respond_to :json

    def index
      respond_with Campusunit.all
    end

    def show
      @campusunit = Campusunit.find(params[:id])
      respond_with @campusunit
    end

    def new
      @campusunit = Campusunit.new
      respond_with @campusunit
    end

    def create
      @campusunit = Campusunit.new(campusunit_params)
      if @campusunit.save
        respond_with @campusunit
      else
        respond_with @campusunit.errors
      end
    end

    def edit
      respond_with Campusunit.find(params[:id])
    end

    def update
      @campusunit = Campusunit.find(params[:id])
      if @campusunit.update_attributes(campusunit_params)
        respond_with :no_content
      else
        respond_with @campusunit.errors
      end
    end

    def destroy
      @campusunit = Campusunit.find(params[:id])
      @campusunit.destroy
      respond_with :no_content
    end

    private

    def set_campusunit
      @campusunit = Campusunit.find(params[:id])
    end

    def campusunit_params
      params.require(:campusunit).permit(:name, :address)
    end

  end

end

app/controllers/campusunits_controller.rb
# -*- encoding : utf-8 -*-
class CampusunitsController < ApplicationController

  before_action :set_campusunit , only: [:show, :edit, :update, :destroy]

  def index
    @campusunits = Campusunit.all
  end

  def show
  end

  def new
    @campusunit = Campusunit.new
  end

  def create
    @campusunit = Campusunit.new(campusunit_params)

    if @campusunit.save
      redirect_to(@campusunit, :notice => 'Campus adicionado com sucesso.')
    else
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if @campusunit.update(campusunit_params)
      redirect_to(@campusunit, :notice => 'O Campus foi atualizado com sucesso.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @campusunit.destroy
    redirect_to campusunits_url
  end

  private

  def set_campusunit
    @campusunit = Campusunit.find(params[:id])
    @restaurants = Restaurant.where(:campusunit_id => @campusunit.id)
  end

  def campusunit_params
    params.require(:campusunit).permit(:name, :address)
  end

end

app/helpers/campusunits_helper.rb
module CampusunitsHelper
end

app/views/campusunits/_form.html.erb
<%= form_for(@campusunit) do |f| %>
<% if @campusunit.errors.any? %>
<div id="explicacao_erro">
	<h2>Devido a estes <%= pluralize(@campusunit.errors.count, "error") %> este novo Campus não pode ser salvo:</h2>
	<ul>
		<% @campusunit.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class='row' >
	<div class='col-sm-6' >
		<div class='form-group'>
			<%= f.label :Nome %><br />
			<%= f.text_field :name ,:class => "form-control"  %>
		</div>
	</div>
</div>
<div class='row' >
	<div class='col-sm-8' >
		<div class='form-group'>
			<%= f.label :Endereço %><br />
			<%= f.text_field :address, :class => "form-control"  %>
		</div>
	</div>
</div>
<div class='row' >
	<div class='col-sm-6' >
		<div class='form-group'>
			<%= f.submit  :class => "btn btn-primary" %>
<% end %>

app/views/campusunits/destroy.html.erb
<h1>Campusunits#destroy</h1>
<p>Find me in app/views/campusunits/destroy.html.erb</p>

app/views/campusunits/edit.html.erb
<h1>Editando Campus</h1>
<%= render 'form' %>

<%= link_to 'Exibir', @campusunit, :class => 'btn btn-info' %>
<%= link_to 'Voltar', campusunits_path, :class => 'btn btn-default'  %>

app/views/campusunits/index.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Campus</h4></div>

  <table class="table table-striped table-hover" style="width:90%; " align="center" id="tableLevels">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Endereço</th>
       <!--  <th width="20%"><%#= t '.actions', :default => t("helpers.actions") %></th> -->
      </tr>
    </thead>

    <tbody>
      <% @campusunits.each do |campus| %>
      <tr>
        <td><%= campus.name %></td>
        <td><%= campus.address %></td>
        <!--  <td><%#= link_to 'Edit', edit_level_path(level) , :class => 'btn btn-xs btn-success'  %>
                <%#= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-xs btn-danger' %>
              </td> -->
      </tr>
      <% end %>
    </tbody>
  </table>

<hr>
<%= link_to 'Novo Campus', new_campusunit_path, :class => 'btn btn-xs btn-primary' %>

app/views/campusunits/new.html.erb
<h1>Novo Campus</h1>

<%= render 'form' %>

<%= link_to 'Voltar', campusunits_path , :class => 'btn btn-default'%>

</div>
</div>

app/views/campusunits/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Campus <%= @campusunit.name %></h1>
<div style="font-size: 18px;">
	<p>
	  <b>Endereço:</b>
	  <%= @campusunit.address %>
	</p>
</div>

<%= link_to 'Editar', edit_campusunit_path(@campusunit), :class => "btn btn-primary" %>
<%= link_to 'Remover', @campusunit, :confirm => 'Tem certeza?', :method => :delete, :class => "btn btn-danger" %>
<%= link_to 'Voltar', campusunits_path, :class => "btn btn-default" %>

app/views/campusunits/update.html.erb
<h1>Campusunits#update</h1>
<p>Find me in app/views/campusunits/update.html.erb</p>