config/routes.rb
Rails.application.routes.draw do

  get 'places/index'

  get 'places/show'

  get 'places/new'

  get 'places/create'

  get 'places/edit'

  get 'places/update'

  get 'places/destroy'

  get 'placescategories/index'

  get 'placescategories/show'

  get 'placescategories/new'

  get 'placescategories/create'

  get 'placescategories/edit'

  get 'placescategories/update'

  get 'placescategories/destroy'

  get 'restaurantopeninghours/index'

  get 'restaurantopeninghours/show'

  get 'restaurantopeninghours/new'

  get 'restaurantopeninghours/create'

  get 'restaurantopeninghours/edit'

  get 'restaurantopeninghours/update'

  get 'restaurantopeninghours/destroy'

  get 'menuscomments/index'

  get 'menuscomments/show'

  get 'menuscomments/new'

  get 'menuscomments/create'

  get 'menuscomments/edit'

  get 'menuscomments/update'

  get 'menuscomments/destroy'

  get 'menus/index'

  get 'menus/show'

  get 'menus/new'

  get 'menus/create'

  get 'menus/edit'

  get 'menus/update'

  get 'menus/destroy'

  get 'meals/index'

  get 'meals/show'

  get 'meals/new'

  get 'meals/create'

  get 'meals/edit'

  get 'meals/update'

  get 'meals/destroy'

  get 'restaurants/index'

  get 'restaurants/show'

  get 'restaurants/new'

  get 'restaurants/create'

  get 'restaurants/edit'

  get 'restaurants/update'

  get 'restaurants/destroy'

  get 'campusunits/index'

  get 'campusunits/show'

  get 'campusunits/new'

  get 'campusunits/create'

  get 'campusunits/edit'

  get 'campusunits/update'

  get 'campusunits/destroy'

  get 'wellcome/index'

  root 'welcome#index'

  resources :campusunits, :path => "campus"
  resources :restaurants, :path => "restaurante"
  resources :restaurantopeninghours, :path => "horariosrestaurante"
  resources :meals, :path => "refeicao"
  resources :menus, :path => "cardapio"
  resources :menuscomments, :path => "comentariosrefeicao"
  resources :placescategories, :path => "categoriaslocal"
  resources :places, :path => "local"

  namespace :api, defaults: {format: 'json'}  do
      resources :campusunits, :path => "campus"
      resources :meals, :path => "refeicao"
  end

end

app/models/restaurantopeninghour.rb
# -*- encoding : utf-8 -*-
class Restaurantopeninghour < ActiveRecord::Base

  validates_presence_of :restaurant_id, :meal_id, :wday, :open, :close

  belongs_to :restaurant
  belongs_to :meal
end

app/controllers/api/restaurantopeninghours_controller.rb
# -*- encoding : utf-8 -*-
module Api
class RestaurantopeninghoursController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghours = Restaurantopeninghour.all

    respond_to do |format|
      format.html #index.html.erb
      format.xml { render :xml => @restaurantopeninghours }
      format.json {render :json => @restaurantopeninghours.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} }
    end
  end

  def show
    @restaurantopeninghour = Restaurantopeninghour.find(params[:id])

    @restaurant = Restaurant.where(:id => @restaurantopeninghour.restaurant_id).first
    @meal = Meal.where(:id => @restaurantopeninghour.meal_id).first

    respond_to do |format|
      format.html #show.html.erb
      format.xml { render :xml => {:restaurant => @restaurant, :meal => @meal, :restaurantopeninghour => @restaurantopeninghour} }
      format.json { render :json => {:restaurant => @restaurant, :meal => @meal, :restaurantopeninghour => @restaurantopeninghour}.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} }
    end
  end

  def new
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghour = Restaurantopeninghour.new

    respond_to do |format|
      format.html #new.html.erb
      format.json { render :json => @restaurantopeninghour.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} }
    end
  end

  def create
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghour = Restaurantopeninghour.new(params[:restaurantopeninghour])

    respond_to do |format|
      if @restaurantopeninghour.save
        format.html { redirect_to(@restaurantopeninghour,
                      :notice => 'Horário salvo com sucesso.')}
        format.json { render :json => @restaurantopeninghour.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")},
                      :status => :created, :location => @restaurantopeninghour }
      else
        format.html { render :action => "new"}
        format.json { render :json => @restaurantopeninghour.errors.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")},
                      :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghour = Restaurantopeninghour.find(params[:id])
  end

  def update
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghour = Restaurantopeninghour.find(params[:id])

    respond_to do |format|
      if @restaurantopeninghour.update_attributes(params[:restaurantopeninghour])
        format.html { redirect_to(@restaurantopeninghour,
                      :notice => 'O horário foi atualizado com sucesso')}
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @restaurantopeninghour.errors.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")},
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurantopeninghour = Restaurantopeninghour.find(params[:id])
    @restaurantopeninghour.destroy

    respond_to do |format|
      format.html { redirect_to restaurantopeninghours_url }
      format.json { head :no_content }
    end
  end

end
end

app/controllers/restaurantopeninghours_controller.rb
# -*- encoding : utf-8 -*-
class RestaurantopeninghoursController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghours = Restaurantopeninghour.all
    
    respond_to do |format|
      format.html #index.html.erb
      format.xml { render :xml => @restaurantopeninghours }
      format.json {render :json => @restaurantopeninghours.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} }
    end
  end

  def show
    @restaurantopeninghour = Restaurantopeninghour.find(params[:id])
    
    @restaurant = Restaurant.where(:id => @restaurantopeninghour.restaurant_id).first
    @meal = Meal.where(:id => @restaurantopeninghour.meal_id).first
    
    respond_to do |format|
      format.html #show.html.erb
      format.xml { render :xml => {:restaurant => @restaurant, :meal => @meal, :restaurantopeninghour => @restaurantopeninghour} }
      format.json { render :json => {:restaurant => @restaurant, :meal => @meal, :restaurantopeninghour => @restaurantopeninghour}.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} }
    end
  end

  def new
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghour = Restaurantopeninghour.new
    
    respond_to do |format|
      format.html #new.html.erb
      format.json { render :json => @restaurantopeninghour.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} }
    end
  end

  def create
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghour = Restaurantopeninghour.new(params[:restaurantopeninghour])
    
    respond_to do |format|
      if @restaurantopeninghour.save
        format.html { redirect_to(@restaurantopeninghour,
                      :notice => 'Horário salvo com sucesso.')}
        format.json { render :json => @restaurantopeninghour.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")},
                      :status => :created, :location => @restaurantopeninghour }
      else
        format.html { render :action => "new"}
        format.json { render :json => @restaurantopeninghour.errors.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")},
                      :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghour = Restaurantopeninghour.find(params[:id])
  end

  def update
    @restaurants = Restaurant.all
    @meals = Meal.all
    @restaurantopeninghour = Restaurantopeninghour.find(params[:id])
    
    respond_to do |format|
      if @restaurantopeninghour.update_attributes(params[:restaurantopeninghour])
        format.html { redirect_to(@restaurantopeninghour,
                      :notice => 'O horário foi atualizado com sucesso')}
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @restaurantopeninghour.errors.to_json.to_s.gsub(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")},
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurantopeninghour = Restaurantopeninghour.find(params[:id])
    @restaurantopeninghour.destroy
    
    respond_to do |format|
      format.html { redirect_to restaurantopeninghours_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/restaurantopeninghours_helper.rb
# -*- encoding : utf-8 -*-
module RestaurantopeninghoursHelper
end

app/views/restaurantopeninghours/_form.html.erb
<%= form_for(@restaurantopeninghour) do |f| %>
	<% if @restaurantopeninghour.errors.any? %>
	<div id="explicacao_erro">
		<h2>Devido a estes <%= pluralize(@restaurantopeninghour.errors.count, "error") %> 
			este novo horário não pode ser salvo:</h2>
		
		<ul>
			<% @restaurantopeninghour.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	
	<div class="campo_form">
		<%= f.label :restaurant %><br />
		<% @restaurants.each_with_index do |r, i| %>
			<%= f.radio_button(:restaurant_id, r.id, :checked => (i == 0 or r.id == @restaurantopeninghour.restaurant_id)? true:false ) %>
			<%= r.name %><br /> 
		<% end %>
	</div>
	<div class="campo_form">
		<%= f.label :meal %><br />
		<% @meals.each_with_index do |m, i| %>
			<%= f.radio_button(:meal_id, m.id, :checked => ( i == 0 or m.id == @restaurantopeninghour.meal_id)? true:false ) %>
			<%= m.name %><br /> 
		<% end %>
	</div>
	<div class="campo_form">
		<%= f.label :wday %><br />
		<% (0..6).each_with_index do |wd, i| %>
			<%= f.radio_button(:wday, wd, :checked => ( i == 0 or wd == @restaurantopeninghour.wday)? true:false ) %>
			<%= "Segunda-Feira" if wd == 1	%> 
			<%= "Terça-Feira" 	if wd == 2 	%>
			<%= "Quarta-Feira" 	if wd == 3 	%>
			<%= "Quinta-Feira" 	if wd == 4 	%>
			<%= "Sexta-Feira" 	if wd == 5	%>
			<%= "Sábado" 		if wd == 6 	%> 
			<%= "Domingo" 		if wd == 0	%>
			<br />
		<% end %>
	</div>
	<div class="campo_form">
		<%= f.label :open %><br />
		<%= f.text_field :open %>
	</div>
	<div class="campo_form">
		<%= f.label :close %><br />
		<%= f.text_field :close %>
	</div>
	<div class="botao_enviar">
		<%= f.submit %>
	</div>
<% end %>

app/views/restaurantopeninghours/create.html.erb
<h1>Restaurantopeninghours#create</h1>
<p>Find me in app/views/restaurantopeninghours/create.html.erb</p>

app/views/restaurantopeninghours/destroy.html.erb
<h1>Restaurantopeninghours#destroy</h1>
<p>Find me in app/views/restaurantopeninghours/destroy.html.erb</p>

app/views/restaurantopeninghours/edit.html.erb
<h1>Restaurantopeninghours#edit</h1>
<p>Find me in app/views/restaurantopeninghours/edit.html.erb</p>

Editando horários da refeição no restaurante

<%= render 'form' %>

<%= link_to 'Exibir', @restaurantopeninghour %> |
<%= link_to 'Voltar', restaurantopeninghours_path %>

app/views/restaurantopeninghours/index.html.erb
<h1>Restaurantopeninghours#index</h1>
<p>Find me in app/views/restaurantopeninghours/index.html.erb</p>

app/views/restaurantopeninghours/new.html.erb
<h1>Restaurantopeninghours#new</h1>
<p>Find me in app/views/restaurantopeninghours/new.html.erb</p>

<h1>Novo Horário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', restaurantopeninghours_path %>

app/views/restaurantopeninghours/show.html.erb
<h1>Restaurantrestaurantopeninghours#show</h1>
<p>Find me in app/views/restaurantrestaurantopeninghours/show.html.erb</p>

<p id="notice"><%= notice %></p>

<p>
  <b>Restaurante:</b>
  <%= @restaurantopeninghour.restaurant.name %>
</p>

<p>
  <b>Refeição:</b>
  <%= @restaurantopeninghour.meal.name %>
</p>

<p>
  <b>Dia da semana:</b>
  	<%= "Segunda-Feira" if @restaurantopeninghour.wday == 1	%> 
	<%= "Terça-Feira" 	if @restaurantopeninghour.wday == 2 %>
	<%= "Quarta-Feira" 	if @restaurantopeninghour.wday == 3 %>
	<%= "Quinta-Feira" 	if @restaurantopeninghour.wday == 4 %>
	<%= "Sexta-Feira" 	if @restaurantopeninghour.wday == 5	%>
	<%= "Sábado" 		if @restaurantopeninghour.wday == 6 %>
	<%= "Domingo" 		if @restaurantopeninghour.wday == 0	%> 
</p>

<p>
  <b>Abre:</b>
  <%= @restaurantopeninghour.open %>
</p>

<p>
  <b>Fecha:</b>
  <%= @restaurantopeninghour.close %>
</p>
 
<%= link_to 'Editar', edit_restaurantopeninghour_path(@restaurantopeninghour) %> | 
<%= link_to 'Remover', @restaurantopeninghour, :confirm => 'Tem certeza?', :method => :delete %> | 
<%= link_to 'Voltar', restaurantopeninghours_path %> 

app/views/restaurantopeninghours/update.html.erb
<h1>Restaurantopeninghours#update</h1>
<p>Find me in app/views/restaurantopeninghours/update.html.erb</p>